# tell Travis to spin up a ruby 2.2.0 environment
language: ruby
rvm:
- 2.2

before_script:
 - echo GH_TOKEN ${GH_TOKEN}
 - echo EMAIL ${EMAIL}
 - echo TRAVIS_BUILD_NUMBER ${TRAVIS_BUILD_NUMBER}
 - echo GITHUB_REPO ${GITHUB_REPO}
 - bundle update
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

# after building, copy the site into the gh-pages branch
# and push back to Github
 after_success:
 - git config github-oauth.github.com ${GH_TOKEN}
 - git config user.name "Travis CI"
 - git config user.email ${EMAIL}
 - rsync -az --delete --exclude '.git*' ../_site/ .
 - touch .nojekyll
 - git add -A .
 - git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
# - git push --force "https://${GH_TOKEN}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/tumble1999/tumble1999.github.io.git
  - REPO_TARGET_BRANCH: master

before_deploy:
  - git config github-oauth.github.com ${GH_TOKEN}
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q "https://${GH_TOKEN}${GITHUB_REPO}" --tags
  - ls -R

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  #file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: false
